<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.5.0.8</Version>
    <Authors>joshua88wa</Authors>
    <Company></Company>
    <Description>Clickable list of nearby targetable players, for healing and raising in Field Operations.</Description>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
